#!/bin/bash
# sctunnel v2 installer — generated by v2/build.sh, do not edit by hand.
#
# Usage:
#   curl -fsSL https://sctunnel1.seucondominio.com.br/install.sh | bash -s -- <cliente_id>

set -euo pipefail

# ── placeholders filled at build time ──────────────────────────────────────
SC_SERVER_HOST="@@SC_SERVER_HOST@@"
SC_TUNNEL_HOST="@@SC_TUNNEL_HOST@@"
SC_TUNNEL_USER="@@SC_TUNNEL_USER@@"
SC_TOKEN="@@SC_TOKEN@@"
BUILD_VERSION="@@BUILD_VERSION@@"
INSTALLER_URL="https://${SC_TUNNEL_HOST}/install.sh"

CLIENTE_ID="${1:-}"

# Quando rodado via `curl | bash`, $0 é "bash" e não dá pra reler o payload.
# Resolve baixando o script para um tempfile e re-execing a partir dele.
if [[ ! -f "$0" || ! -r "$0" ]]; then
  SELF=$(mktemp /tmp/sctunnel_install.XXXXXX.sh)
  trap 'rm -f "$SELF"' EXIT
  curl -fsSL "$INSTALLER_URL" -o "$SELF" || { echo "ERRO: falha ao re-baixar $INSTALLER_URL" >&2; exit 1; }
  chmod +x "$SELF"
  exec bash "$SELF" "$@"
fi

print_h() { printf '\n\033[1;34m== %s ==\033[0m\n' "$*"; }
ok()      { printf '\033[0;32m✔ %s\033[0m\n' "$*"; }
warn()    { printf '\033[0;33m⚠ %s\033[0m\n' "$*"; }
die()     { printf '\033[0;31m✘ %s\033[0m\n' "$*" >&2; exit 1; }

[[ "$(uname -s)" == "Linux" ]] || die "v2 installer is Linux-only"
[[ -n "$CLIENTE_ID" ]] || die "Uso: install.sh <cliente_id>  (ex.: install.sh 51)"
[[ "$CLIENTE_ID" =~ ^[0-9]+$ ]] || die "cliente_id deve ser numérico (recebido: '$CLIENTE_ID')"

if [[ "$EUID" -ne 0 ]]; then
  command -v sudo >/dev/null || die "precisa de root ou sudo"
  exec sudo -E env CLIENTE_ID="$CLIENTE_ID" bash "$0" "$CLIENTE_ID"
fi

BASE=/opt/sctunnel
print_h "sctunnel v2 install (build $BUILD_VERSION)"
echo "cliente_id: $CLIENTE_ID"
echo "base dir:   $BASE"

# ── deps ───────────────────────────────────────────────────────────────────
print_h "instalando dependências do sistema"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
  python3 python3-venv python3-pip python3-dev \
  build-essential libffi-dev libpcap-dev \
  jq libcap2-bin openssh-client cron
ok "apt deps ok"

# ── extract embedded payload ───────────────────────────────────────────────
print_h "extraindo payload embutido"
mkdir -p "$BASE" "$BASE/logs"

PAYLOAD_LINE=$(awk '/^__PAYLOAD_BELOW__$/{print NR+1; exit 0}' "$0")
[[ -n "$PAYLOAD_LINE" ]] || die "payload marker não encontrado neste install.sh"

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

tail -n +"$PAYLOAD_LINE" "$0" | base64 -d | tar -xzf - -C "$TMPDIR"

# bundle layout: runtime/* + scTunnel.pem
[[ -f "$TMPDIR/scTunnel.pem" ]] || die "PEM ausente no payload"
[[ -f "$TMPDIR/runtime/tunnels.py" ]] || die "runtime ausente no payload"

cp -f "$TMPDIR"/runtime/*.py "$BASE/"
cp -f "$TMPDIR"/runtime/run.sh "$BASE/"
cp -f "$TMPDIR"/runtime/set_cliente.sh "$BASE/"
chmod +x "$BASE/run.sh" "$BASE/set_cliente.sh"

install -m 600 -o root -g root "$TMPDIR/scTunnel.pem" "$BASE/scTunnel.pem"
ok "código + PEM extraídos para $BASE"

# ── config.json ────────────────────────────────────────────────────────────
print_h "escrevendo config.json"
cat > "$BASE/config.json" <<JSON
{
  "sc_server": {
    "host": "$SC_SERVER_HOST",
    "token": "$SC_TOKEN",
    "cliente_id": $CLIENTE_ID,
    "equipamento_codigos": [],
    "tipo_script": "python"
  },
  "sc_tunnel_server": {
    "host": "$SC_TUNNEL_HOST",
    "user": "$SC_TUNNEL_USER"
  }
}
JSON
chmod 600 "$BASE/config.json"
echo "$CLIENTE_ID" > "$BASE/cliente.txt"

# Captura o usuário humano que instalou (não "root") para a mensagem
# "Acesse essa máquina" ficar com login utilizável.
LOGIN_USER="${SUDO_USER:-${USER:-}}"
if [[ -z "$LOGIN_USER" || "$LOGIN_USER" == "root" ]]; then
  for cand in orangepi ubuntu pi admin; do
    id "$cand" &>/dev/null && LOGIN_USER="$cand" && break
  done
fi
LOGIN_USER="${LOGIN_USER:-ubuntu}"
echo "$LOGIN_USER" > "$BASE/ssh_user"
ok "config.json + cliente.txt gravados (cliente_id=$CLIENTE_ID, ssh_user=$LOGIN_USER)"

# ── venv + pip deps ────────────────────────────────────────────────────────
print_h "criando venv e instalando libs python"
if [[ ! -d "$BASE/venv" ]]; then
  python3 -m venv "$BASE/venv"
fi
"$BASE/venv/bin/pip" install --quiet --upgrade pip
"$BASE/venv/bin/pip" install --quiet --upgrade \
  scapy psutil requests
ok "libs ok ($("$BASE/venv/bin/python" -V))"

# ── cap_net_raw on the venv python ─────────────────────────────────────────
print_h "concedendo cap_net_raw ao Python da venv"
PYREAL=$(readlink -f "$BASE/venv/bin/python")
setcap cap_net_raw+eip "$PYREAL"
if getcap "$PYREAL" | grep -q cap_net_raw; then
  ok "cap_net_raw aplicado em $PYREAL"
else
  warn "falha ao aplicar cap_net_raw — varredura ARP pode falhar"
fi

# ── set_cliente global command ─────────────────────────────────────────────
print_h "instalando comando global set_cliente"
cat > /usr/local/bin/set_cliente <<EOF
#!/bin/bash
exec $BASE/set_cliente.sh "\$@"
EOF
chmod +x /usr/local/bin/set_cliente
ok "set_cliente disponível globalmente"

# ── cron ───────────────────────────────────────────────────────────────────
print_h "instalando cron"
CRON=/etc/cron.d/sctunnel
cat > "$CRON" <<EOF
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
@reboot      root /opt/sctunnel/run.sh >> /opt/sctunnel/logs/cron.log 2>&1
*/1 * * * *  root /opt/sctunnel/run.sh >> /opt/sctunnel/logs/cron.log 2>&1
EOF
chmod 644 "$CRON"
systemctl restart cron 2>/dev/null || service cron restart 2>/dev/null || true
ok "cron instalado em $CRON"

# ── ownership ──────────────────────────────────────────────────────────────
chown -R root:root "$BASE"
chmod 600 "$BASE/scTunnel.pem" "$BASE/config.json"
chmod 755 "$BASE"
chmod 755 "$BASE/logs"

# ── primeiro run sincrono ──────────────────────────────────────────────────
print_h "executando primeira rodada"
"$BASE/run.sh" || warn "primeira execução retornou erro — veja $BASE/logs/tunnels.log"

print_h "instalação concluída"
echo
ok "cliente_id $CLIENTE_ID conectado"
echo
echo "comandos:"
echo "  set_cliente <id>           # trocar cliente"
echo "  /opt/sctunnel/run.sh       # rodar manualmente"
echo "  tail -f /opt/sctunnel/logs/tunnels.log"
echo
exit 0

# Nada deve aparecer entre o exit acima e o marcador abaixo.
__PAYLOAD_BELOW__
